#!/usr/bin/env node

// Magic Markers for auto-configuration
// #%# family=auto
// #%# capabilities=autoconf suggest

var sys = require("sys")
  , exec = require("child_process").exec
  , mode = "fetch"

// could be "config" or "autoconf" mode
if (process.argv[2] !== undefined) mode = process.argv[2]

function get_cpu_usage(process_filter, graph_name) {
  var cpu = 0
  exec("top -b -n 1 | grep " + process_filter, function(err, data) {
    data = data.split("\n")
    data.pop()
    data.forEach(function(line) {
      var values = line.replace(/^\s+/, "").replace(/\s+$/, "").split(/\s+/)
      cpu += parseFloat(values[8])
    })

    sys.puts(graph_name + ".value " + (cpu * 10000))
  })
}

exec("cat /proc/stat |egrep '^cpu[0-9]+'|wc -l", function(err, ncpu) {
  ncpu = parseInt(ncpu)
  var percent = ncpu * 100
    , maximum = percent
    , limit = percent

  if (mode === 'config') {
    sys.puts("graph_title Adserver CPU usage")
    sys.puts("graph_args --base 1000 -r --lower-limit 0 --upper-limit " + limit)
    sys.puts("graph_vlabel %")
    sys.puts("graph_period second")
    sys.puts("graph_category adserver")
    sys.puts("graph_scale no")

    sys.puts("adserver_web_cpu.label adserver_web cpu")
    sys.puts("adserver_web_cpu.draw AREA")
    sys.puts("adserver_web_cpu.max " + maximum)
    sys.puts("adserver_web_cpu.min 0")
    sys.puts("adserver_web_cpu.type DERIVE")

    sys.puts("adserver_cache_cpu.label adserver_cache cpu")
    sys.puts("adserver_cache_cpu.draw STACK")
    sys.puts("adserver_cache_cpu.max " + maximum)
    sys.puts("adserver_cache_cpu.min 0")
    sys.puts("adserver_cache_cpu.type DERIVE")

    sys.puts("adserver_master_cpu.label adserver_master cpu")
    sys.puts("adserver_master_cpu.draw STACK")
    sys.puts("adserver_master_cpu.max " + maximum)
    sys.puts("adserver_master_cpu.min 0")
    sys.puts("adserver_master_cpu.type DERIVE")
  } else {
    get_cpu_usage("adserver_web", "adserver_web_cpu")
    get_cpu_usage("adserver_cache", "adserver_cache_cpu")
    get_cpu_usage("adserver_master", "adserver_master_cpu")
  }
})

