#!/usr/bin/env node
// Munin plugin for CouchDB database doc count

// Magic Markers for auto-configuration
// #%# family=auto
// #%# capabilities=autoconf suggest

var sys = require("sys")
  , http = require("http")

if (process.argv[2] == "config") {
  sys.puts("graph_title Conversions")
  sys.puts("graph_args --base 1000")
  sys.puts("graph_vlabel conversions/s")
  sys.puts("graph_category adserver")

  sys.puts('conversion_success.min 0')
  sys.puts('conversion_success.type DERIVE')
  sys.puts("conversion_success.label success")
  sys.puts("conversion_success.draw AREA")

  sys.puts('conversion_error.min 0')
  sys.puts('conversion_error.type DERIVE')
  sys.puts("conversion_error.label error")
  sys.puts("conversion_error.draw STACK")

}
else {
  var data = ""
    , chunk = ""

  var request = http.createClient(8888, "127.0.0.1").request('GET', '/counters');
  request.end();

  request.on('response', function (response) {
    response.on('data', function (chunk) {
      data += chunk
    })

    response.on("end", function() {
      var counters = JSON.parse(data)

      sys.puts("conversion_error.value " + counters.adserver.conversionError)
      sys.puts("conversion_success.value " + counters.adserver.conversionSuccess)

    })
  })
}
