#!/usr/bin/env node

// Magic Markers for auto-configuration
// #%# family=auto
// #%# capabilities=autoconf suggest

var sys = require("sys")
  , http = require("http")

if (process.argv[2] == "config") {
  sys.puts("graph_title Placement Requests filtered by Geo-IP")
  sys.puts("graph_args --base 1000")
  sys.puts("graph_vlabel requests/s")
  sys.puts("graph_category adserver")
  sys.puts("graph_info This graphs shows how many placement requests have been filtered duo to the geographical location of the requests origin.")

  sys.puts('geo_filtered_requests.min 0')
  sys.puts('geo_filtered_requests.type DERIVE')
  sys.puts('geo_filtered_requests.label geo filtered requests')
}
else {
  var data = ""
    , chunk = ""

  var request = http.createClient(8888, "127.0.0.1").request('GET', '/counters')
  request.end()

  request.on('response', function (response) {
    response.on('data', function (chunk) {
      data += chunk
    })

    response.on("end", function() {
      var counters = JSON.parse(data)
      sys.puts('geo_filtered_requests.value ' + counters.adserver.filteredRequestByIP)
    })
  })
}
