#!/usr/bin/env node
// Munin plugin for CouchDB database doc count

// Magic Markers for auto-configuration
// #%# family=auto
// #%# capabilities=autoconf suggest

var sys = require("sys")
  , http = require("http")

if (process.argv[2] == "config") {
  sys.puts("graph_title Redirect Requests")
  sys.puts("graph_args --base 1000")
  sys.puts("graph_vlabel Ratio")
  sys.puts("graph_category adserver")

  sys.puts('redirect.min 0')
  sys.puts('redirect.type DERIVE')
  sys.puts("redirect.label req/s")
}
else {
  var data = ""
    , chunk = ""

  var request = http.createClient(8888, "127.0.0.1").request('GET', '/counters');
  request.end();

  request.on('response', function (response) {
    response.on('data', function (chunk) {
      data += chunk
    })

    response.on("end", function() {
      var counters = JSON.parse(data)

      sys.puts("redirect.value " + counters.adserver.redirect)

    })
  })
}
