#! /bin/env ruby

require 'rubygems'
require 'redis'

$0 =~ /_(\d+_\d+_\d+_\d+)_(\d+)$/
ip, port = $1, $2
ip = ip.nil? ? '127.0.0.1' : ip.gsub!(/_/, '.')
port = port.nil? ? 6379 : port

config = ARGV.any? { |a| a =~ /config/ }

if config
  puts "graph_title Redis keyspace hits/misses rate"
  puts "graph_category redis"
  puts "graph_vlabel commands/s"
  puts "graph_info This graph monitors the redis keyspace hits and misses"
  puts "graph_args --base 1000"

  puts "keyspace_hits.label hits/s"
  puts "keyspace_hits.type DERIVE"
  puts "keyspace_hits.draw AREA"
  puts "keyspace_hits.min 0"

  puts "keyspace_misses.label hits/s"
  puts "keyspace_misses.type DERIVE"
  puts "keyspace_misses.draw STACK"
  puts "keyspace_misses.min 0"
else
  redis = Redis.new(:host => ip, :port => port)
  info  = redis.info

  puts "keyspace_hits.value" + " " + info['keyspace_hits'].to_s
  puts "keyspace_misses.value" + " " + info['keyspace_misses'].to_s
end
