#!/usr/bin/env ruby

require 'rubygems'

require 'yajl'
require 'open-uri'

if ARGV.any? { |a| a =~ /config/ }
  puts "graph_title vnode gets & puts"
  puts "graph_args --base 1000"
  puts "graph_vlabel number of gets (-) and puts (+) / \${graph_period}"
  puts "graph_category riak"

  puts "vnode_gets.label vnode_gets"
  puts "vnode_gets.graph no"
  puts "vnode_gets.type COUNTER"
  puts "vnode_gets.min 0"
  puts "vnode_gets.max 1000000"

  puts "vnode_puts.label vnode gets/puts"
  puts "vnode_puts.type COUNTER"
  puts "vnode_puts.min 0"
  puts "vnode_puts.max 1000000"
  puts "vnode_puts.negative vnode_gets"
else
  statistics = Yajl::Parser.parse(open "http://localhost:8098/stats")

  puts "vnode_gets.value #{statistics["vnode_gets_total"] || 0}"
  puts "vnode_puts.value #{statistics["vnode_puts_total"] || 0}"
end
